apiVersion: apps/v1
kind: Deployment
metadata:
  name: standings-service-deployment
  labels:
    app: standings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standings-service
  template:
    metadata:
      labels:
        app: standings-service
    spec:
      containers:
      - name: standings-service
        imagePullPolicy: IfNotPresent
        image: segment17hub/standingsservice:0.1
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: standings-service
  labels:
    app: standings-service
spec:
  type: ClusterIP
  selector:
    app: standings-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: standings-service
spec:
  grpc: True
  prefix: /ubc_package.StandingsService/
  rewrite: /ubc_package.StandingsService/
  service: standings-service:50051
---
