apiVersion: apps/v1
kind: Deployment
metadata:
  name: standings-service-deployment
  labels:
    app: standings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standings-service
  template:
    metadata:
      labels:
        app: standings-service
    spec:
      containers:
      - name: standings-service
        imagePullPolicy: IfNotPresent
        image: segment17hub/standingsservice:0.1.1
        ports:
        - containerPort: 50054
        env:
          - name: MATCH_SERVICE_ADDR
            value: "match-service:50053"
          - name: STANDINGS_SERVICE_ADDR
            value: "standings-service:50054"
---
apiVersion: v1
kind: Service
metadata:
  name: standings-service
  labels:
    app: standings-service
spec:
  type: ClusterIP
  selector:
    app: standings-service
  ports:
    - name: grpc
      port: 50054
      targetPort: 50054
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: standings-service
spec:
  grpc: True
  prefix: /ubc_package.StandingsService/
  rewrite: /ubc_package.StandingsService/
  service: standings-service:50054
---
