apiVersion: apps/v1
kind: Deployment
metadata:
  name: standings-service-deployment
  labels:
    app: standings-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: standings-service
  template:
    metadata:
      labels:
        app: standings-service
    spec:
      containers:
      - name: standings-service
        imagePullPolicy: Never
        image: segment17hub/standingsservice
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: standings-service
  labels:
    app: standings-service
spec:
  type: ClusterIP
  selector:
    app: standings-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
